export const recipes = {
  recipes: {
    icon: "textures/ui/icon_crafting.png",
    title: "guide.common.recipes",
    body: "guide.common.recipes.desc",
    buttons: [
      "recipes_mob_spawner",
      "recipes_copper_golem_spawn_egg",
      "recipes_allay_spawn_egg",
      "recipes_armadillo_spawn_egg",
      "recipes_axolotl_spawn_egg",
      "recipes_bat_spawn_egg",
      "recipes_bee_spawn_egg",
      "recipes_blaze_spawn_egg",
      "recipes_bogged_spawn_egg",
      "recipes_breeze_spawn_egg",
      "recipes_camel_spawn_egg",
      "recipes_cat_spawn_egg",
      "recipes_cave_spider_spawn_egg",
      "recipes_chicken_spawn_egg",
      "recipes_cod_spawn_egg",
      "recipes_cow_spawn_egg",
      "recipes_creaking_spawn_egg",
      "recipes_creeper_spawn_egg",
      "recipes_dolphin_spawn_egg",
      "recipes_donkey_spawn_egg",
      "recipes_drowned_spawn_egg",
      "recipes_elder_guardian_spawn_egg",
      "recipes_enderman_spawn_egg",
      "recipes_endermite_spawn_egg",
      "recipes_evoker_spawn_egg",
      "recipes_fox_spawn_egg",
      "recipes_frog_spawn_egg",
      "recipes_ghast_spawn_egg",
      "recipes_glow_squid_spawn_egg",
      "recipes_goat_spawn_egg",
      "recipes_guardian_spawn_egg",
      "recipes_happy_ghast_spawn_egg",
      "recipes_hoglin_spawn_egg",
      "recipes_horse_spawn_egg",
      "recipes_husk_spawn_egg",
      "recipes_iron_golem_spawn_egg",
      "recipes_llama_spawn_egg",
      "recipes_magma_cube_spawn_egg",
      "recipes_mooshroom_spawn_egg",
      "recipes_mule_spawn_egg",
      "recipes_ocelot_spawn_egg",
      "recipes_panda_spawn_egg",
      "recipes_parrot_spawn_egg",
      "recipes_phantom_spawn_egg",
      "recipes_pig_spawn_egg",
      "recipes_piglin_brute_spawn_egg",
      "recipes_piglin_spawn_egg",
      "recipes_pillager_spawn_egg",
      "recipes_polar_bear_spawn_egg",
      "recipes_pufferfish_spawn_egg",
      "recipes_rabbit_spawn_egg",
      "recipes_ravager_spawn_egg",
      "recipes_salmon_spawn_egg",
      "recipes_sheep_spawn_egg",
      "recipes_shulker_spawn_egg",
      "recipes_silverfish_spawn_egg",
      "recipes_skeleton_horse_spawn_egg",
      "recipes_skeleton_spawn_egg",
      "recipes_slime_spawn_egg",
      "recipes_sniffer_spawn_egg",
      "recipes_snow_golem_spawn_egg",
      "recipes_spider_spawn_egg",
      "recipes_squid_spawn_egg",
      "recipes_stray_spawn_egg",
      "recipes_strider_spawn_egg",
      "recipes_tadpole_spawn_egg",
      "recipes_tropical_fish_spawn_egg",
      "recipes_turtle_spawn_egg",
      "recipes_vex_spawn_egg",
      "recipes_villager_spawn_egg",
      "recipes_vindicator_spawn_egg",
      "recipes_wandering_trader_spawn_egg",
      "recipes_warden_spawn_egg",
      "recipes_witch_spawn_egg",
      "recipes_wither_skeleton_spawn_egg",
      "recipes_wolf_spawn_egg",
      "recipes_zoglin_spawn_egg",
      "recipes_zombie_horse_spawn_egg",
      "recipes_zombie_spawn_egg",
      "recipes_zombie_villager_spawn_egg",
      "recipes_zombified_piglin_spawn_egg",
    ],
  },
  recipes_mob_spawner: {
    icon: "textures/lpsm/spawner_craft/ui/mob_spawner",
    title: "tile.mob_spawner.name",
    body: "#recipes.mob_spawner.desc",
  },
  recipes_copper_golem_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_copper_golem",
    title: "item.spawn_egg.entity.copper_golem.name",
    body: "#recipes.copper_golem_spawn_egg.desc",
  },
  recipes_allay_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_allay",
    title: "item.spawn_egg.entity.allay.name",
    body: "#recipes.allay_spawn_egg.desc",
  },
  recipes_armadillo_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_armadillo",
    title: "item.spawn_egg.entity.armadillo.name",
    body: "#recipes.armadillo_spawn_egg.desc",
  },
  recipes_axolotl_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_axolotl",
    title: "item.spawn_egg.entity.axolotl.name",
    body: "#recipes.axolotl_spawn_egg.desc",
  },
  recipes_bat_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_bat",
    title: "item.spawn_egg.entity.bat.name",
    body: "#recipes.bat_spawn_egg.desc",
  },
  recipes_bee_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_bee",
    title: "item.spawn_egg.entity.bee.name",
    body: "#recipes.bee_spawn_egg.desc",
  },
  recipes_blaze_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_blaze",
    title: "item.spawn_egg.entity.blaze.name",
    body: "#recipes.blaze_spawn_egg.desc",
  },
  recipes_bogged_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_bogged",
    title: "item.spawn_egg.entity.bogged.name",
    body: "#recipes.bogged_spawn_egg.desc",
  },
  recipes_breeze_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_breeze",
    title: "item.spawn_egg.entity.breeze.name",
    body: "#recipes.breeze_spawn_egg.desc",
  },
  recipes_camel_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_camel",
    title: "item.spawn_egg.entity.camel.name",
    body: "#recipes.camel_spawn_egg.desc",
  },
  recipes_cat_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_cat",
    title: "item.spawn_egg.entity.cat.name",
    body: "#recipes.cat_spawn_egg.desc",
  },
  recipes_cave_spider_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_cave_spider",
    title: "item.spawn_egg.entity.cave_spider.name",
    body: "#recipes.cave_spider_spawn_egg.desc",
  },
  recipes_chicken_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_chicken",
    title: "item.spawn_egg.entity.chicken.name",
    body: "#recipes.chicken_spawn_egg.desc",
  },
  recipes_cod_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_cod",
    title: "item.spawn_egg.entity.cod.name",
    body: "#recipes.cod_spawn_egg.desc",
  },
  recipes_cow_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_cow",
    title: "item.spawn_egg.entity.cow.name",
    body: "#recipes.cow_spawn_egg.desc",
  },
  recipes_creaking_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_creaking",
    title: "item.spawn_egg.entity.creaking.name",
    body: "#recipes.creaking_spawn_egg.desc",
  },
  recipes_creeper_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_creeper",
    title: "item.spawn_egg.entity.creeper.name",
    body: "#recipes.creeper_spawn_egg.desc",
  },
  recipes_dolphin_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_dolphin",
    title: "item.spawn_egg.entity.dolphin.name",
    body: "#recipes.dolphin_spawn_egg.desc",
  },
  recipes_donkey_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_donkey",
    title: "item.spawn_egg.entity.donkey.name",
    body: "#recipes.donkey_spawn_egg.desc",
  },
  recipes_drowned_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_drowned",
    title: "item.spawn_egg.entity.drowned.name",
    body: "#recipes.drowned_spawn_egg.desc",
  },
  recipes_elder_guardian_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_elder_guardian",
    title: "item.spawn_egg.entity.elder_guardian.name",
    body: "#recipes.elder_guardian_spawn_egg.desc",
  },
  recipes_enderman_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_enderman",
    title: "item.spawn_egg.entity.enderman.name",
    body: "#recipes.enderman_spawn_egg.desc",
  },
  recipes_endermite_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_endermite",
    title: "item.spawn_egg.entity.endermite.name",
    body: "#recipes.endermite_spawn_egg.desc",
  },
  recipes_evoker_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_evoker",
    title: "item.spawn_egg.entity.evocation_illager.name",
    body: "#recipes.evoker_spawn_egg.desc",
  },
  recipes_fox_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_fox",
    title: "item.spawn_egg.entity.fox.name",
    body: "#recipes.fox_spawn_egg.desc",
  },
  recipes_frog_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_frog",
    title: "item.spawn_egg.entity.frog.name",
    body: "#recipes.frog_spawn_egg.desc",
  },
  recipes_ghast_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_ghast",
    title: "item.spawn_egg.entity.ghast.name",
    body: "#recipes.ghast_spawn_egg.desc",
  },
  recipes_glow_squid_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_glow_squid",
    title: "item.spawn_egg.entity.glow_squid.name",
    body: "#recipes.glow_squid_spawn_egg.desc",
  },
  recipes_goat_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_goat",
    title: "item.spawn_egg.entity.goat.name",
    body: "#recipes.goat_spawn_egg.desc",
  },
  recipes_guardian_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_guardian",
    title: "item.spawn_egg.entity.guardian.name",
    body: "#recipes.guardian_spawn_egg.desc",
  },
  recipes_happy_ghast_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_happy_ghast",
    title: "item.spawn_egg.entity.happy_ghast.name",
    body: "#recipes.happy_ghast_spawn_egg.desc",
  },
  recipes_hoglin_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_hoglin",
    title: "item.spawn_egg.entity.hoglin.name",
    body: "#recipes.hoglin_spawn_egg.desc",
  },
  recipes_horse_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_horse",
    title: "item.spawn_egg.entity.horse.name",
    body: "#recipes.horse_spawn_egg.desc",
  },
  recipes_husk_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_husk",
    title: "item.spawn_egg.entity.husk.name",
    body: "#recipes.husk_spawn_egg.desc",
  },
  recipes_iron_golem_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_iron_golem",
    title: "item.spawn_egg.entity.iron_golem.name",
    body: "#recipes.iron_golem_spawn_egg.desc",
  },
  recipes_llama_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_llama",
    title: "item.spawn_egg.entity.llama.name",
    body: "#recipes.llama_spawn_egg.desc",
  },
  recipes_magma_cube_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_magma_cube",
    title: "item.spawn_egg.entity.magma_cube.name",
    body: "#recipes.magma_cube_spawn_egg.desc",
  },
  recipes_mooshroom_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_mooshroom",
    title: "item.spawn_egg.entity.mooshroom.name",
    body: "#recipes.mooshroom_spawn_egg.desc",
  },
  recipes_mule_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_mule",
    title: "item.spawn_egg.entity.mule.name",
    body: "#recipes.mule_spawn_egg.desc",
  },
  recipes_ocelot_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_ocelot",
    title: "item.spawn_egg.entity.ocelot.name",
    body: "#recipes.ocelot_spawn_egg.desc",
  },
  recipes_panda_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_panda",
    title: "item.spawn_egg.entity.panda.name",
    body: "#recipes.panda_spawn_egg.desc",
  },
  recipes_parrot_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_parrot",
    title: "item.spawn_egg.entity.parrot.name",
    body: "#recipes.parrot_spawn_egg.desc",
  },
  recipes_phantom_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_phantom",
    title: "item.spawn_egg.entity.phantom.name",
    body: "#recipes.phantom_spawn_egg.desc",
  },
  recipes_pig_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_pig",
    title: "item.spawn_egg.entity.pig.name",
    body: "#recipes.pig_spawn_egg.desc",
  },
  recipes_piglin_brute_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_piglin_brute",
    title: "item.spawn_egg.entity.piglin_brute.name",
    body: "#recipes.piglin_brute_spawn_egg.desc",
  },
  recipes_piglin_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_piglin",
    title: "item.spawn_egg.entity.piglin.name",
    body: "#recipes.piglin_spawn_egg.desc",
  },
  recipes_pillager_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_pillager",
    title: "item.spawn_egg.entity.pillager.name",
    body: "#recipes.pillager_spawn_egg.desc",
  },
  recipes_polar_bear_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_polar_bear",
    title: "item.spawn_egg.entity.polar_bear.name",
    body: "#recipes.polar_bear_spawn_egg.desc",
  },
  recipes_pufferfish_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_pufferfish",
    title: "item.spawn_egg.entity.pufferfish.name",
    body: "#recipes.pufferfish_spawn_egg.desc",
  },
  recipes_rabbit_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_rabbit",
    title: "item.spawn_egg.entity.rabbit.name",
    body: "#recipes.rabbit_spawn_egg.desc",
  },
  recipes_ravager_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_ravager",
    title: "item.spawn_egg.entity.ravager.name",
    body: "#recipes.ravager_spawn_egg.desc",
  },
  recipes_salmon_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_salmon",
    title: "item.spawn_egg.entity.salmon.name",
    body: "#recipes.salmon_spawn_egg.desc",
  },
  recipes_sheep_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_sheep",
    title: "item.spawn_egg.entity.sheep.name",
    body: "#recipes.sheep_spawn_egg.desc",
  },
  recipes_shulker_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_shulker",
    title: "item.spawn_egg.entity.shulker.name",
    body: "#recipes.shulker_spawn_egg.desc",
  },
  recipes_silverfish_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_silverfish",
    title: "item.spawn_egg.entity.silverfish.name",
    body: "#recipes.silverfish_spawn_egg.desc",
  },
  recipes_skeleton_horse_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_skeleton_horse",
    title: "item.spawn_egg.entity.skeleton_horse.name",
    body: "#recipes.skeleton_horse_spawn_egg.desc",
  },
  recipes_skeleton_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_skeleton",
    title: "item.spawn_egg.entity.skeleton.name",
    body: "#recipes.skeleton_spawn_egg.desc",
  },
  recipes_slime_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_slime",
    title: "item.spawn_egg.entity.slime.name",
    body: "#recipes.slime_spawn_egg.desc",
  },
  recipes_sniffer_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_sniffer",
    title: "item.spawn_egg.entity.sniffer.name",
    body: "#recipes.sniffer_spawn_egg.desc",
  },
  recipes_snow_golem_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_snow_golem",
    title: "item.spawn_egg.entity.snow_golem.name",
    body: "#recipes.snow_golem_spawn_egg.desc",
  },
  recipes_spider_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_spider",
    title: "item.spawn_egg.entity.spider.name",
    body: "#recipes.spider_spawn_egg.desc",
  },
  recipes_squid_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_squid",
    title: "item.spawn_egg.entity.squid.name",
    body: "#recipes.squid_spawn_egg.desc",
  },
  recipes_stray_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_stray",
    title: "item.spawn_egg.entity.stray.name",
    body: "#recipes.stray_spawn_egg.desc",
  },
  recipes_strider_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_strider",
    title: "item.spawn_egg.entity.strider.name",
    body: "#recipes.strider_spawn_egg.desc",
  },
  recipes_tadpole_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_tadpole",
    title: "item.spawn_egg.entity.tadpole.name",
    body: "#recipes.tadpole_spawn_egg.desc",
  },
  recipes_tropical_fish_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_tropicalfish",
    title: "item.spawn_egg.entity.tropicalfish.name",
    body: "#recipes.tropical_fish_spawn_egg.desc",
  },
  recipes_turtle_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_turtle",
    title: "item.spawn_egg.entity.turtle.name",
    body: "#recipes.turtle_spawn_egg.desc",
  },
  recipes_vex_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_vex",
    title: "item.spawn_egg.entity.vex.name",
    body: "#recipes.vex_spawn_egg.desc",
  },
  recipes_villager_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_villager",
    title: "item.spawn_egg.entity.villager.name",
    body: "#recipes.villager_spawn_egg.desc",
  },
  recipes_vindicator_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_vindicator",
    title: "item.spawn_egg.entity.vindicator.name",
    body: "#recipes.vindicator_spawn_egg.desc",
  },
  recipes_wandering_trader_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_wandering_trader",
    title: "item.spawn_egg.entity.wandering_trader.name",
    body: "#recipes.wandering_trader_spawn_egg.desc",
  },
  recipes_warden_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_warden",
    title: "item.spawn_egg.entity.warden.name",
    body: "#recipes.warden_spawn_egg.desc",
  },
  recipes_witch_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_witch",
    title: "item.spawn_egg.entity.witch.name",
    body: "#recipes.witch_spawn_egg.desc",
  },
  recipes_wither_skeleton_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_wither_skeleton",
    title: "item.spawn_egg.entity.wither_skeleton.name",
    body: "#recipes.wither_skeleton_spawn_egg.desc",
  },
  recipes_wolf_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_wolf",
    title: "item.spawn_egg.entity.wolf.name",
    body: "#recipes.wolf_spawn_egg.desc",
  },
  recipes_zoglin_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_zoglin",
    title: "item.spawn_egg.entity.zoglin.name",
    body: "#recipes.zoglin_spawn_egg.desc",
  },
  recipes_zombie_horse_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_zombie_horse",
    title: "item.spawn_egg.entity.zombie_horse.name",
    body: "#recipes.zombie_horse_spawn_egg.desc",
  },
  recipes_zombie_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_zombie",
    title: "item.spawn_egg.entity.zombie.name",
    body: "#recipes.zombie_spawn_egg.desc",
  },
  recipes_zombie_villager_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_zombie_villager",
    title: "item.spawn_egg.entity.zombie_villager.name",
    body: "#recipes.zombie_villager_spawn_egg.desc",
  },
  recipes_zombified_piglin_spawn_egg: {
    icon: "textures/items/spawn_eggs/spawn_egg_zombified_piglin",
    title: "item.spawn_egg.entity.zombie_pigman.name",
    body: "#recipes.zombified_piglin_spawn_egg.desc",
  },
};
